deployment:
  tasks:
    - export DEPLOYPATH=/home/zoq5jjekub4u/public_html
    # Copy all files from dist to public_html, overwriting existing ones (-f)
    - /bin/cp -rf dist/* $DEPLOYPATH/
    # Ensure index.html is exactly what we built
    - /bin/cp -f dist/index.html $DEPLOYPATH/index.html
    # Set permissions
    - /bin/chmod 644 $DEPLOYPATH/index.html
